### ISSUE TITLE
Could not load <class 'idle_time.GnomeWaylandIdleMonitor'>

### ISSUE THREAD

**Issue by IoTCARE** [escaped/idle_time#2]
im getting this error on linux
```
Could not load <class 'idle_time.GnomeWaylandIdleMonitor'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/idle_time/__init__.py", line 31, in get_monitor
    return monitor_class(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/idle_time/__init__.py", line 83, in __init__
    self.connection = connect_and_authenticate(bus="SESSION")
  File "/usr/local/lib/python3.7/dist-packages/jeepney/integrate/blocking.py", line 113, in connect_and_authenticate
    bus_addr = get_bus(bus)
  File "/usr/local/lib/python3.7/dist-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/usr/local/lib/python3.7/dist-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'
```

this is my code:

```
from idle_time import IdleMonitor
idle = None
try:
    monitor = IdleMonitor.get_monitor()
    idle = monitor.get_idle_time()
except:
    idle = None

print(idle)
```

id like to make a crontab to get this info. but i noticed that inst worked.

**Comment by escaped** [comment]
Hey @IoTCARE 

looks like you trying to run this in a non-desktop environment. Thus not all required variables have been set up yet. I did some googeling and it looks you should get it to work if you run 

```
export $(dbus-launch)
```

before you execute your to set all required environment variables.

Source: https://stackoverflow.com/a/41244272

**Comment by TheMasterRoot** [comment]
i have the same problem and how i can export $(dbus-aunch) from inside my python code?

**Comment by escaped** [comment]
Not sure, what's the best way to achieve this. Basically running `export $(dbus-launch)` sets two environment variables: `DBUS_SESSION_BUS_ADDRESS` and `DBUS_SESSION_BUS_PID`. I guess you could try using [`subprocess.check_output`](https://docs.python.org/3/library/subprocess.html#subprocess.check_output) and [`os.environ`](https://docs.python.org/3/library/os.html#os.environ) to extract the values and set them during runtime. The output of `dbus-launch` looks like

```
$ echo $(dbus-launch)                                                                       
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-fQIljhKQUA,guid=c18d630d0188b43baf3493ae5f76ae5b DBUS_SESSION_BUS_PID=168012
```
Something along these lines might work (untested)

```python

import os
import subprocess

# both values need to be set
dbus_initialised = bool(os.getenv('DBUS_SESSION_BUS_ADDRESS')) and bool(os.getenv('DBUS_SESSION_BUS_PID'))

if not dbus_initialised:
    dbus_output = subprocess.check_output("dbus-launch").decode('utf8').strip()
    # extract values and update environment
    for name_and_value in output.split('\n'):
        name, value = name_and_value.split('=', 1)
        os.environ[name] = value
```

Though, I think it would be easier to run your script/program using `export $(dbus-launch) && python your_file.py`.
